dist: bionic
language: cpp
compiler: clang
install:
  - wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | sudo apt-key add -
  - sudo apt-add-repository 'deb https://apt.kitware.com/ubuntu/ bionic main'
  - sudo apt-add-repository 'deb https://apt.kitware.com/ubuntu/ bionic-rc main'
  - sudo apt update
  - sudo apt install cmake
  - sudo apt install ninja-build
script: ./.build.sh
